services:
  mysql:
    image: mysql:8.0
    container_name: practice-mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    container_name: practice-redis
    ports:
      - "6379:6379"
